services:

  app:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
